# Google API Key 설정
# Google AI Studio에서 API Key를 발급받아 아래에 입력하세요
# https://aistudio.google.com

GOOGLE_API_KEY = "your-google-api-key-here"

# 예시:
# GOOGLE_API_KEY = "AIzaSyD-9tSrke72PouQMnMX-a7UUUUUUUUUUUU" 